version: '3.9'
services:
    nginx:
        container_name: nginx
        image: nginx:1.19.6
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./config:/etc/nginx/conf.d
            - ./html:/var/www/html
            - ./ssl:/etc/ssl/certs
        networks:
            - webnet
        logging:
            driver: 'json-file'
            options:
                max-size: '8m'
                max-file: '10'
        restart: always
networks:
    webnet:
        name: webnet
        driver: bridge
